"""Numerical/reference tests; run with: python3 -m unittest discover -s dev-docs/algorithms -v."""
import dataclasses
import math
import unittest
from datetime import datetime, timedelta, timezone

from fsrs6 import Card, Scheduler


T = datetime(2026, 9, 23, tzinfo=timezone.utc)


class FSRS6Tests(unittest.TestCase):
    def setUp(self):
        self.scheduler = Scheduler()

    def test_curve_definition_and_inverse(self):
        for stability in (.001, .2, 2.3065, 10, 1000):
            self.assertAlmostEqual(self.scheduler.recall(0, stability), 1)
            self.assertAlmostEqual(self.scheduler.recall(stability, stability), .9)
            for target in (.7, .85, .9, .95, .97):
                interval = self.scheduler.interval(stability, target)
                self.assertAlmostEqual(self.scheduler.recall(interval, stability), target)

    def test_curve_decreases_with_elapsed_time(self):
        values = [self.scheduler.recall(t, 10) for t in (0, 1, 5, 10, 30, 100)]
        self.assertEqual(values, sorted(values, reverse=True))
        self.assertLess(Scheduler(retention=.95).interval(10), self.scheduler.interval(10))

    def test_upstream_sequence(self):
        # Generated by pinned py-fsrs 9446cb0, 10m steps, fuzz off; never generated by this kernel.
        expected = [
            (3, 2.3065, 2.118103970459016, 'review', 172800),
            (3, 10.964332335820698, 2.111214235785395, 'review', 950400),
            (3, 46.28021728755693, 2.1043313908464483, 'review', 3974400),
            (1, 2.9325804541638116, 7.389975788014609, 'relearning', 600),
            (3, 2.9325804541638116, 7.377814181523433, 'review', 259200),
            (3, 7.794549965290449, 7.365664736638748, 'review', 691200),
        ]
        card, now = Card(), T
        for grade, stability, difficulty, phase, seconds in expected:
            card = self.scheduler.review(card, grade, now)
            self.assertAlmostEqual(card.stability, stability, places=10)
            self.assertAlmostEqual(card.difficulty, difficulty, places=10)
            self.assertEqual(card.phase, phase)
            self.assertEqual((card.due - now).total_seconds(), seconds)
            now = card.due

    def test_first_grade_and_single_learning_step(self):
        for grade, phase, seconds in [(1,'learning',600),(2,'learning',900),(3,'review',172800),(4,'review',691200)]:
            result = self.scheduler.review(Card(), grade, T)
            self.assertEqual(result.phase, phase)
            self.assertEqual((result.due-T).total_seconds(),seconds)

    def test_short_term_success_does_not_reduce_stability(self):
        old = Card(100, 5, 'review', T, T+timedelta(days=100))
        for grade in (2,3,4):
            updated = self.scheduler.review(old,grade,T+timedelta(minutes=10))
            self.assertGreaterEqual(updated.stability,old.stability)

    def test_lapse_retains_positive_state_and_schedules_relearning(self):
        old = Card(100, 5, 'review', T, T+timedelta(days=100))
        result = self.scheduler.review(old,1,T+timedelta(days=100))
        self.assertGreaterEqual(result.stability,.001)
        self.assertLess(result.stability,old.stability)
        self.assertEqual(result.phase,'relearning')
        self.assertEqual(result.due-result.last_review,timedelta(minutes=10))

    def test_input_is_immutable_and_replay_deterministic(self):
        card = Card()
        a = self.scheduler.review(card,3,T)
        self.assertEqual(card,Card())
        self.assertEqual(a,self.scheduler.review(card,3,T))
        with self.assertRaises(dataclasses.FrozenInstanceError):
            a.stability = 99

    def test_invalid_input_is_rejected(self):
        for grade in (0,5,3.0,True):
            with self.assertRaises(ValueError): self.scheduler.review(Card(),grade,T)
        for retention in (0,1,math.nan):
            with self.assertRaises(ValueError): Scheduler(retention=retention)
        with self.assertRaises(ValueError): self.scheduler.review(Card(),3,T.replace(tzinfo=None))
        with self.assertRaises(ValueError): self.scheduler.review(Card(math.nan,5,'review',T,T),3,T)
        with self.assertRaises(ValueError): self.scheduler.review(Card(1,None,'review',T,T),3,T)
        with self.assertRaises(ValueError): Scheduler(weights=(1,)*19)

    def test_clock_rollback_is_not_a_review(self):
        card = self.scheduler.review(Card(),3,T)
        with self.assertRaises(ValueError): self.scheduler.review(card,3,T-timedelta(seconds=1))

    def test_full_elapsed_days_contract(self):
        card=self.scheduler.review(Card(),3,T)
        a=self.scheduler.review(card,3,T+timedelta(hours=24))
        b=self.scheduler.review(card,3,T+timedelta(hours=47))
        self.assertEqual(a.stability,b.stability)
        self.assertEqual(a.difficulty,b.difficulty)

    def test_rounding_and_interval_bounds(self):
        self.assertEqual(self.scheduler.scheduled_days(.001),1)
        self.assertEqual(self.scheduler.scheduled_days(2.5),2)
        self.assertEqual(Scheduler(maximum_days=365).scheduled_days(10000),365)


if __name__ == '__main__':
    unittest.main()
