/// Which dictionary an entry came from, in a form a ledger row can be keyed by.
///
/// The display name is not that form: it changes with the interface language
/// (`dev-docs/study-unit.md` §5.2). The bundle identifier is, where there is one — and for the
/// sideloaded conversions there is none, which is a fact about them worth carrying rather than
/// papering over.
public struct DictionaryIdentity: Codable, Sendable, Equatable, Hashable {
    /// What the reader sees: "New Oxford American Dictionary", "牛津英汉汉英词典".
    public let name: String
    /// `com.apple.dictionary.NOAD`. Nil for a sideloaded conversion — measured empty for all three
    /// enabled on this Mac.
    public let identifier: String?
    /// The bundle's `CFBundleShortVersionString`: NOAD 2.6, 牛津英汉汉英 1.1 as measured. A sense key
    /// is only meaningful inside one version of a dictionary, so the ledger keeps it.
    public let version: String?

    public init(name: String, identifier: String? = nil, version: String? = nil) {
        self.name = name
        self.identifier = identifier
        self.version = version
    }

    /// What the ledger stores. The bundle identifier where there is one; otherwise the display
    /// name, marked as such so a row keyed by a name is never mistaken for one keyed by an
    /// identifier — and so a dictionary that later gains an identifier does not silently merge
    /// with its own older rows.
    public var key: String { identifier ?? "name:\(name)" }

    /// Whether this dictionary's entry ids survive the reader importing it again. Apple's assets
    /// carry the publisher's ids; a sideloaded conversion's are generated by whatever tool built
    /// the bundle — `_myk`, `_2878`, `_dxt` — and change on the next import, so a ledger keyed to
    /// them survives only by luck (`dev-docs/dictionary-markup.md` §7).
    public var hasStableEntryIDs: Bool { identifier != nil }
}
