import DictionaryModel
import Foundation
import XiaolaiDictCore
import Testing

/// What a ledger row and a study card hang on.
///
/// `dev-docs/dictionary-markup.md` §7: the sideloaded conversions carry an entry id like every
/// Apple entry does, but theirs is generated by whatever tool built the bundle — `_myk`, `_2878`,
/// `_dxt` — and changes on the next import. Three of the seven dictionaries enabled on this Mac
/// are sideloaded, so keying a ledger to those ids orphans the reader's study list the next time
/// they re-import a dictionary.
struct EntryKeyTests {
    private let apple = DictionaryIdentity(
        name: "New Oxford American Dictionary", identifier: "com.apple.dictionary.NOAD")
    /// A sideloaded conversion has no bundle identifier — measured empty for every one enabled here.
    private let sideloaded = DictionaryIdentity(name: "Longman Dictionary of Contemporary English")

    private func entry(
        _ dictionary: DictionaryIdentity, headword: String, id: String?, homograph: String? = nil
    ) -> DictionaryEntry {
        DictionaryEntry(
            dictionary: dictionary, headword: headword, lookedUp: headword, html: "<p/>",
            document: EntryDocument(isStyled: true, entryID: id, homograph: homograph))
    }

    /// The failure this type exists to prevent: the reader re-imports Longman, every entry id in
    /// the bundle changes, and a study list keyed to the old ones points at nothing.
    @Test func aSideloadedEntryKeepsItsKeyWhenTheBundleIsImportedAgain() {
        let before = entry(sideloaded, headword: "hold", id: "_myk")
        let after = entry(sideloaded, headword: "hold", id: "_2878")
        #expect(before.entryKey == after.entryKey)
        #expect(before.entryKey != nil)
    }

    /// Where the ids are the publisher's they are the key, because they are what separates the
    /// homographs a headword alone would merge.
    @Test func anAppleEntryIsKeyedByItsPublisherID() {
        #expect(entry(apple, headword: "fine", id: "m_en_gbus0362760").entryKey == "m_en_gbus0362760")
    }

    /// Marked for the same reason `DictionaryIdentity.key` marks a display name: a row keyed by
    /// headword must never be mistaken for one keyed by a publisher id, and a dictionary that
    /// later gains a bundle identifier must not silently merge with its own older rows.
    @Test func aHeadwordKeyIsMarkedSoItCannotBeMistakenForAPublisherID() {
        let key = entry(sideloaded, headword: "hold", id: "_myk").entryKey
        #expect(key != "hold")
        #expect(key?.hasPrefix("headword:") == true)
    }

    /// Two entries sharing a headword are two study items, not one — *fine* the penalty is not
    /// *fine* the adjective. Where the dictionary numbers them, the key says so.
    @Test func homographsOfASideloadedEntryStayApart() {
        let first = entry(sideloaded, headword: "fine", id: "_a", homograph: "1")
        let second = entry(sideloaded, headword: "fine", id: "_b", homograph: "2")
        #expect(first.entryKey != second.entryKey)
    }

    /// A dictionary whose ids *are* stable, on an entry that declared none, is a malformed entry
    /// rather than a dictionary without ids — and the id was the thing separating its homographs.
    /// Unknown, never guessed.
    @Test func anAppleEntryDeclaringNoIDHasNoKey() {
        #expect(entry(apple, headword: "fine", id: nil).entryKey == nil)
    }
}
